### ISSUE TITLE
FaceLivenessDetector error: Failed to start the face liveness session

### ISSUE THREAD

**Issue by BochaXD** [raichandramohan27ca/amplify-flutter-face-liveness#3]
I am using the face_liveness_detector Flutter package (^0.2.0) with AWS Rekognition Face Liveness.
When starting the liveness session, I always get this error:
`FaceLivenessDetector error: FaceLivenessDetectionException: Failed to start the face liveness session.`

The sessionId is new, valid, and in "CREATED" status (checked via backend).
Region is set to 'us-west-2'.
Permissions for camera are granted.
The widget is initialized as follows:
```
FaceLivenessDetector(
  sessionId: _sessionId,
  region: _region,
  onComplete: _onLivenessComplete,
  onError: _onLivenessError,
)
```
Dependencies in pubspec.yaml:
```
dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  face_liveness_detector: ^0.2.0
  cupertino_icons: ^1.0.8
  http: ^1.1.0
```
Tested on a physical device.
No errors in AWS logs or backend.
Question:
Is there any extra configuration required for Flutter?
Any known issues or suggestions to resolve this error?

i use config for android
